import {TelemetryGroup} from "@/features/telemetry/telemetry.types";

export const TELEMETRY_GROUPS: TelemetryGroup[] = [
    // ───────── ACTIVE POWER ─────────
    {
        id: 'system_power',
        label: 'Active power',
        keys: 'P',
        unit: 'W',
        phaseScope: 'SYSTEM',
        category: 'POWER',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'phase_power',
        label: 'Active power (φ)',
        keys: 'P1,P2,P3',
        unit: 'W',
        phaseScope: 'PHASE',
        category: 'POWER',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── REACTIVE POWER ─────────
    {
        id: 'system_reactive_power',
        label: 'Reactive power',
        keys: 'Q',
        unit: 'var',
        phaseScope: 'SYSTEM',
        category: 'REACTIVE_POWER',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'phase_reactive_power',
        label: 'Reactive power (φ)',
        keys: 'Q1,Q2,Q3',
        unit: 'var',
        phaseScope: 'PHASE',
        category: 'REACTIVE_POWER',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── APPARENT POWER ─────────
    {
        id: 'system_apparent_power',
        label: 'Apparent power',
        keys: 'S',
        unit: 'VA',
        phaseScope: 'SYSTEM',
        category: 'APPARENT_POWER',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'phase_apparent_power',
        label: 'Apparent power (φ)',
        keys: 'S1,S2,S3',
        unit: 'VA',
        phaseScope: 'PHASE',
        category: 'APPARENT_POWER',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── VOLTAGE ─────────
    {
        id: 'phase_voltage_ln',
        label: 'Phase-neutral voltage',
        keys: 'V1,V2,V3',
        unit: 'V',
        phaseScope: 'PHASE',
        category: 'VOLTAGE',
        chartType: 'line',
        agg: 'AVG',
        favorite: true,
    },
    {
        id: 'phase_voltage_ll',
        label: 'Line-to-line voltage',
        keys: 'U1,U2,U3',
        unit: 'V',
        phaseScope: 'PHASE',
        category: 'VOLTAGE',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'system_voltage',
        label: 'System voltage',
        keys: 'U',
        unit: 'V',
        phaseScope: 'SYSTEM',
        category: 'VOLTAGE',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── CURRENT ─────────
    {
        id: 'phase_current',
        label: 'Current (φ)',
        keys: 'I1,I2,I3',
        unit: 'A',
        phaseScope: 'PHASE',
        category: 'CURRENT',
        chartType: 'line',
        agg: 'AVG',
        favorite: true,
    },
    {
        id: 'neutral_current',
        label: 'Neutral current',
        keys: 'In',
        unit: 'A',
        phaseScope: 'SYSTEM',
        category: 'CURRENT',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'system_current',
        label: 'Current',
        keys: 'I',
        unit: 'A',
        phaseScope: 'SYSTEM',
        category: 'CURRENT',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── FREQUENCY ─────────
    {
        id: 'frequency',
        label: 'Frequency',
        keys: 'F',
        unit: 'Hz',
        phaseScope: 'SYSTEM',
        category: 'FREQUENCY',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── POWER FACTOR ─────────
    {
        id: 'power_factor_system',
        label: 'Power factor',
        keys: 'PF',
        unit: '',
        phaseScope: 'SYSTEM',
        category: 'POWER_FACTOR',
        chartType: 'line',
        agg: 'AVG',
    },
    {
        id: 'power_factor_phase',
        label: 'Power factor (φ)',
        keys: 'PF1,PF2,PF3',
        unit: '',
        phaseScope: 'PHASE',
        category: 'POWER_FACTOR',
        chartType: 'line',
        agg: 'AVG',
    },

    // ───────── ACTIVE ENERGY (DERIVADA TUYA) ─────────
    {
        id: 'system_energy',
        label: 'Energy',
        keys: 'Edelta',
        unit: 'Wh',
        phaseScope: 'SYSTEM',
        category: 'ENERGY',
        chartType: 'bar',
        agg: 'SUM',
        favorite: true,
    },
    {
        id: 'phase_energy',
        label: 'Energy (φ)',
        keys: 'E1delta,E2delta,E3delta',
        unit: 'Wh',
        phaseScope: 'PHASE',
        category: 'ENERGY',
        chartType: 'bar',
        agg: 'SUM',
    },

    // ───────── EXPORT ENERGY ─────────
    {
        id: 'system_energy_export',
        label: 'Exported energy',
        keys: 'Ex',
        unit: 'Wh',
        phaseScope: 'SYSTEM',
        category: 'ENERGY_EXPORT',
        chartType: 'bar',
        agg: 'SUM',
    },
    {
        id: 'phase_energy_export',
        label: 'Exported energy (φ)',
        keys: 'Ex1,Ex2,Ex3',
        unit: 'Wh',
        phaseScope: 'PHASE',
        category: 'ENERGY_EXPORT',
        chartType: 'bar',
        agg: 'SUM',
    },

    // ───────── REACTIVE ENERGY ─────────
    {
        id: 'system_reactive_energy',
        label: 'Reactive energy',
        keys: 'RE',
        unit: 'varh',
        phaseScope: 'SYSTEM',
        category: 'REACTIVE_ENERGY',
        chartType: 'bar',
        agg: 'SUM',
    },
    {
        id: 'phase_reactive_energy',
        label: 'Reactive energy (φ)',
        keys: 'RE1,RE2,RE3',
        unit: 'varh',
        phaseScope: 'PHASE',
        category: 'REACTIVE_ENERGY',
        chartType: 'bar',
        agg: 'SUM',
    },

    // ───────── APPARENT ENERGY ─────────
    {
        id: 'system_apparent_energy',
        label: 'Apparent energy',
        keys: 'AE',
        unit: 'VAh',
        phaseScope: 'SYSTEM',
        category: 'APPARENT_ENERGY',
        chartType: 'bar',
        agg: 'SUM',
    },
    {
        id: 'phase_apparent_energy',
        label: 'Apparent energy (φ)',
        keys: 'AE1,AE2,AE3',
        unit: 'VAh',
        phaseScope: 'PHASE',
        category: 'APPARENT_ENERGY',
        chartType: 'bar',
        agg: 'SUM',
    },
]
